/****************************************************************************
NAME
    Lang_EN.h

DESCRIPTION

REFERENCE

MODIFICATION SHEET:
    MODIFIED   (YYYY.MM.DD)
    LinHB     2012.12.31      - created
****************************************************************************/
#ifndef _LANG_EN_H 
#define _LANG_EN_H


unsigned char STR_DEFAUT_NUMERO_PAD_PRINC_EN[] = "0156291628";
unsigned char STR_DEFAUT_NUMERO_PAD_SEC_EN[] = "0156291628";
unsigned char STR_DEFAUT_ADRESSE_X25_EN[] = "195314853500";
unsigned char STR_AUTHENTIFICATION_EN[] = "CONNECT SERV ABM";
unsigned char STR_EUR_EN[] = "EUR";
unsigned char STR_BLANC_EN[] = "                 ";
unsigned char STR_TAB_EN[] = "    ";
unsigned char STR_AUTHENTI_PAP_EN[] = "PAP";
unsigned char STR_AUTHENTI_SHAP_EN[] = "SHAP";
unsigned char STR_VIDE_EN[] = " ";
unsigned char STR_ETOILES_EN[] = "         *****";
unsigned char STR_GPRS_EN[] = "GPRS";
unsigned char STR_PPP_EN[] = "PPP";
unsigned char STR_ETOILES2_EN[] = "************************";
unsigned char STR_TIRETS_EN[] = "------------------------";
unsigned char STR_CHOIX_OPERATEUR_EN[] = "SELECT NETWORK:";
unsigned char STR_PASSWORD_DISPLAY_EN[] = "PASSWORD";
unsigned char STR_ERROR_EN[] = "ERROR:";
unsigned char STR_COUPER_LE_TICKET_EN[] = "TAKE VOUCHER";
unsigned char STR_PRESS_ENTER_EN[] = "PRESS ENTER";
unsigned char STR_VAL_CANCEL_EN[] = "VAL/CANCEL?";
unsigned char STR_VAL_CANCEL_COR_EN[] = "VAL/CANCEL/COR?";
unsigned char STR_IDENT_MANAGER_EN[] = "ID MANAGER :";
unsigned char STR_PASSWORD_SECRET_EN[] = "PASSWORD MANAGER";
unsigned char STR_PASSWORDS_CASHIERS_EN[] = "PASSW. CASHIERS";
unsigned char STR_PASSWORD_CASHIER_EN[] = "PASS CASHIER";
unsigned char STR_TIME_SOFTWAREDOWNLOAD_EN[] = "SOFTW.LOAD TIME";
unsigned char STR_TIME_SALESPOLLING_EN[] = "POLLING TIME";
unsigned char STR_TIME_SETTINGSDOWNLOAD_EN[] = "SETT. LOAD TIME";
unsigned char STR_PRINT_PARAM_EN[] = "PRINT SETTINGS";
unsigned char STR_NUMERO_PAD_EN[] = "PAD PRINCIPAL :";
unsigned char STR_NUMERO_PAD_SECOURS_EN[] = "PAD SECONDARY :";
unsigned char STR_MENU_PPP_EN[] = "PPP MENU:";
unsigned char STR_NUM_TLCHGT_EN[] = "DOWNLOAD SERVER:";
unsigned char STR_ID_TERMINAL_EN[] = "TERMINAL ID:";
unsigned char STR_TYPE_IMPRIMANTE_EN[] = "PRINTER TYPE:";
unsigned char STR_REINIT_APPLI_EN[] = "SOFTW. RESET ";
unsigned char STR_INFOS_TRACE_EN[] = "LOG LEVEL:";
unsigned char STR_NUMEROTATION_EN[] = "DIALLING";
unsigned char STR_FIN_CONNEXION_EN[] = "DISCONNECTING";
unsigned char STR_PRINT_EN[] = "PRINTING";
unsigned char STR_ON_GOING_EN[] = "ONGOING";
unsigned char STR_TICKET_CLIENT_EN[] = "CLIENT VOUCHER";
unsigned char STR_TICKET_MANAGER_EN[] = "MERCHANT TICKET";
unsigned char STR_DUPLICATA2_EN[] = "DUPLICATA";
unsigned char STR_NON_DISPONIBLE_EN[] = "UNAVAILABLE";
unsigned char STR_PAS_D_OPERATION_EN[] = "NO TRANSACTION";
unsigned char STR_DONE_EN[] = "DONE";
unsigned char STR_DEJA_PRESENT_EN[] = "ALREADY CHOOSEN";
unsigned char STR_REPORT_COMMER_EN[] = "MANAGER REPORT";
unsigned char STR_REPORT_CASHIER_EN[] = "CASHIER REPORT";
unsigned char STR_REPORT_DAILY_EN[] = "DAILY REPORT?";
unsigned char STR_EFFACEMENT_DES_EN[] = "ERASE ";
unsigned char STR_RAPP_VAL_ANN_EN[] = "REPORT VAL/CANC?";
unsigned char STR_PASSWORD_MANAGER_EN[] = "PASSW. MANAGER ?";
unsigned char STR_ENTRER_CODE_EN[] = "ENTER PASSWORD :";
unsigned char STR_REPORTS_EN[] = "REPORTS";
unsigned char STR_APPLICATION_EN[] = "SOFTWARE";
unsigned char STR_INITIALISEE_EN[] = "RESET";
unsigned char STR_PARAMETRES_APPLI_EN[] = "SOFTW. SETTINGS";
unsigned char STR_INCOMPLETS_EN[] = "INCOMPLETE";
unsigned char STR_TICKET_ABANDON_EN[] = "CANCELED";
unsigned char STR_ATTENTE_REPONSE_EN[] = "WAIT";
unsigned char STR_SERVEUR_EN[] = "SERVER";
unsigned char STR_MEMOIRE_PLEINE_EN[] = "MEMORY FULL";
unsigned char STR_ACTIVER_TELECH_EN[] = "ACTIV. DOWNLOAD";
unsigned char STR_ANNUL_TELECH_EN[] = "DESACTIV.DOWNLOAD";
unsigned char STR_TELECHARGEMENT_EN[] = "SOFTWARE DOWNLOAD";
unsigned char STR_ACTIVE_EN[] = "ON";
unsigned char STR_DESACTIVE_EN[] = "OFF";
unsigned char STR_MODIFICATION_EN[] = "AMEND";
unsigned char STR_ENTRER_LE_CODE_EN[] = "ENTER PASSWORD :";
unsigned char STR_CONNEXION_OK_EN[] = "CONNECTING OK ";
unsigned char STR_NUMEROTATION_OK_EN[] = "DIALING OK";
unsigned char STR_CONNEXION_EN[] = "CONNECTING  ";
unsigned char STR_SERVEUR_KO_EN[] = "SERVER DOWN ";
unsigned char STR_NUMERO_OCCUPE_EN[] = "BUSY TONE ";
unsigned char STR_NUMERO_INTERDIT_EN[] = "FORBIDDEN DIAL ";
unsigned char STR_PAS_DE_PORTEUSE_EN[] = "NO CARRIER ";
unsigned char STR_LINE_ABSENTE_EN[] = "NO DIAL TONE";
unsigned char STR_ABANDON_EN[] = "CANCELED";
unsigned char STR_PROBLEME_MODEM_EN[] = "MODEM ERROR";
unsigned char STR_PRODUCT_EN[] = "PRODUCT :";
unsigned char STR_GESTION_RECH_EN[] = "MAX PIN QTY";
unsigned char STR_INGEVOUCHER_EN[] = APP_NAME;
unsigned char STR_RECHARGEMENT_EN[] = "RESTOCK";
unsigned char STR_LANCER_RECHARGE_EN[] = "LAUNCH RESTOCK";
unsigned char STR_PASSWORDS_EN[] = "PINS";
unsigned char STR_TELEPARAMETRAGE_EN[] = "SETTINGS DOWNL.";
unsigned char STR_TELEPARAMETRAGE_PRINT_EN[] = "SETTINGS";
unsigned char STR_A_FAIRE_EN[] = "TO BE DONE";
unsigned char STR_DEJA_EFECTUE_EN[] = "ALREADY DONE";
unsigned char STR_TABLE_OPERATEURS_EN[] = "Table Networks";
unsigned char STR_TABLE_PRODUCTS_EN[] = "Table Products";
unsigned char STR_TABLE_TICKET_EN[] = "Table Tickets";
unsigned char STR_TABLE_MAINTENANCE_EN[] = "Table Maintenance";
unsigned char STR_TABLE_TERMINAL_EN[] = "Table Terminal";
unsigned char STR_TABLE_HORODATAGE_EN[] = "Table Time&Date";
unsigned char STR_ECHEC_EN[] = "ERROR";
unsigned char STR_SUCCES_EN[] = "SUCCES";
unsigned char STR_IDENTIFICATION_EN[] = "IDENTIFICATION";
unsigned char STR_VENTE_EN[] = "SALE";
unsigned char STR_SALESPOLLING_EN[] = "SALES POLLING";
unsigned char STR_INFO_TELECOL_EN[] = "INFO POLLING";
unsigned char STR_DEMANDE_VERSION_EN[] = "RELEASE REQUEST";
unsigned char STR_REEL_EN[] = "REAL V22 BIS";
unsigned char STR_REEL_V22_EN[] = "REAL V22";
unsigned char STR_SIMUL_EN[] = "SIMUL";
unsigned char STR_PINS_EXPIRED_EN[] = "EXPIRED PINS";
unsigned char STR_PINS_EXPIRED2_EN[] = "EXPIRED PINS";
unsigned char STR_PINS_USED_EN[] = "USED PINS";
unsigned char STR_PINS_USED2_EN[] = "USED PINS";
unsigned char STR_ANOMALIE_VENTE_EN[] = "ERROR SALE";
unsigned char STR_ANOMALIE_VENTE2_EN[] = "ERROR SALE";
unsigned char STR_INTERDIT_EN[] = "FORBIDDEN";
unsigned char STR_COMMANDE_EN[] = "ORDER";
unsigned char STR_PARAM_ENREGISTRE_EN[] = "SETTINGS RECORD";
unsigned char STR_VAL_POUR_ENTRER_EN[] = "PRESS ENTER";
unsigned char STR_NOM_CATEGORY_EN[] = "Network:";
unsigned char STR_NOM_PRODUCT_EN[] = "Prod: ";
unsigned char STR_ID_TERMINAL_Min_EN[] = "Terminal Id : ";
unsigned char STR_ID_COMM_EN[] = "Manager Id:";
unsigned char STR_NUM_TRANS_EN[] = "Transac Number:";
unsigned char STR_VALEUR_EN[] = "Value :";
unsigned char STR_No_SERIE_EN[] = "Serial: ";
unsigned char STR_FIN_VALIDITE_EN[] = "Validity Date:";
unsigned char STR_PASSWORD_ERREUR_EN[] = "Error :";
unsigned char STR_Op_Min_EN[] = "Network :";
unsigned char STR_RECAPITULATIF_EN[] = "SUMMARY";
unsigned char STR_NB_CODES_CHARGES_EN[] = "Pins Qty Downloaded:";
unsigned char STR_NB_CODES_A_CHARGER_EN[] = "Nb Pins to down: ";
unsigned char STR_Amount_Tot_EN[] = "Tot. amount:";
unsigned char STR_TOTAL_EN[] = "Total";
unsigned char STR_CASHIER_Min_EN[] = "Cashier :";
unsigned char STR_Nb_Codes_Telecol_EN[] = "Pins Qty Sent:";
unsigned char STR_Envoi_EN[] = "Send";
unsigned char STR_SALESPOLLING2_EN[] = "SALES POLLING";
unsigned char STR_NB_CODES_EN[] = "Pins Nb";
unsigned char STR_TYPE_IMPRIMANTE_Min_EN[] = "Printer Type : ";
unsigned char STR_Serv_MDP_EN[] = "Serv. MDP: ";
unsigned char STR_HOUR_EN[] = "Hour";
unsigned char STR_ETAT_DU_STOCK_EN[] = "STOCK STATE";
unsigned char STR_DISP_EN[] = "Avail";
unsigned char STR_VEND_EN[] = "Sold";
unsigned char STR_IDENT_EN[] = "Id : ";
unsigned char STR_Version_Ticket_EN[] = "Release Tickets    :";
unsigned char STR_Version_Category_EN[] = "Release Networks   :";
unsigned char STR_Version_Product_EN[] = "Release Products   :";
unsigned char STR_Version_Maintenance_EN[] = "Release Maintenance:";
unsigned char STR_Version_Terminal_EN[] = "Release Terminal   :";
unsigned char STR_Version_Horodatage_EN[] = "Release Time&Date  :";
unsigned char STR_RECHARGEMENT_CODES_EN[] = "PINS RESTOCK";
unsigned char STR_REPORT_EN[] = "REPORT";
unsigned char STR_MANAGER_EN[] = "MANAGER";
unsigned char STR_CASHIER_EN[] = "CASHIER";
unsigned char STR_CASHIER_NB_AMOUNT_EN[] = "Cashier  Qty     Amount";
unsigned char STR_PRODUCT_NB_AMOUNT_EN[] = "Product  Qty     Amount";
unsigned char STR_PXUNITAIRE_EN[] = "Unit Price";
unsigned char STR_NB_EN[] = "Qty";
unsigned char STR_AMOUNT_EN[] = "Amount";
unsigned char STR_DUPLICATA_EN[] = "DUPLICATA";
unsigned char STR_TELECHARGEMENT_APPLI_EN[] = "SOFTWARE DOWNLOAD";
unsigned char STR_RECHARGEMENT_CODES_2_EN[] = "RESTOCK PINS";
unsigned char STR_SALESPOLLING_2_EN[] = "SALES POLLING";
unsigned char STR_PAS_DE_TELECH_EN[] = "NO SOFTWARE DOWNLOAD";
unsigned char STR_PAS_DE_RECHARGE_EN[] = "NO RESTOCK";
unsigned char STR_PAS_DE_TELECOL_EN[] = "NO SALES POLLING";
unsigned char STR_PAS_DE_TELEPARA_EN[] = "NO SETTINGS DOWNLOAD";
unsigned char STR_PLUS_DE_CODE_EN[] = "NO MORE PINS";
unsigned char STR_DISPONIBLE_EN[] = "AVAILABLE";
unsigned char STR_ON_LINE_EN[] = "On Line";
unsigned char STR_TITRE_TICKET_PARAMETRE_EN[] = "SETTINGS";
unsigned char STR_SOUS_TITRE_MANAGER_EN[] = "Manager";
unsigned char STR_SOUS_TITRE_PRODUCT_EN[] = "Product";
unsigned char STR_SOUS_TITRE_TERMINAL_EN[] = "Terminal";
unsigned char STR_SOUS_TITRE_CONNEXION_EN[] = "Connection";
unsigned char STR_SOUS_TITRE_TELECHARGEMENT_EN[] = "Download Software";
unsigned char STR_SOUS_TITRE_CASHIERS_EN[] = "Cashiers";
unsigned char STR_SERVICE_EN[] = "Service";
unsigned char STR_DEMARRE_EN[] = "Start";
unsigned char STR_ARRETE_EN[] = "Locked";
unsigned char STR_DEMARRER_SERVICE_EN[] = "Start Service";
unsigned char STR_ARRETER_SERVICE_EN[] = "Lock Service";
unsigned char STR_VISUALISE_STOCK_EN[] = "DISPLAY STOCK";
unsigned char STR_PRINT_STOCK_EN[] = "PRINT STOCK";
unsigned char STR_CHARGER_CLE_EN[] = "LOAD KEY";
unsigned char STR_CHARGEMENT_CLE_EN[] = "LOADING KEY";
unsigned char STR_CREDIT_EPUISE_EN[] = "NO CREDIT";
unsigned char STR_PASSWORD_UPPER_EN[] = "PASSWORD :";
unsigned char STR_REPORT_DAILY_PRINT_EN[] = "DAILY REPORT";
unsigned char STR_STOCK_SERVEUR_EN[] = "SERVER STOCK";
unsigned char STR_EPUISE_EN[] = "EMPTY";
unsigned char STR_NOUVEAU_CODE_EN[] = "NEW PASSWORD:";
unsigned char STR_CONFIRMER_CODE_EN[] = "CONFIRM PASS.:";
unsigned char STR_AUTRE_VENTE_EN[] = "OTHER SALE";
unsigned char STR_PRINT_CODE_BARRE_EN[] = "PRINT BAR CODE ";
unsigned char STR_PRINT_LOGO_EN[] = "PRINT LOGO:";
unsigned char STR_OUI_EN[] = "YES";
unsigned char STR_NON_EN[] = "NO";
unsigned char STR_VALIDE_COMMANDE_EN[] = "CHECK ORDER ?";
unsigned char STR_CHARGEMENT_LOGO_EN[] = "LOGOS DOWNLOAD";
unsigned char STR_MASTER_APPLI_EN[] = "SOFT MASTER :";
unsigned char STR_TYPE_CNX_TELECH_EN[] = "DOWN CNX TYPE:";
unsigned char STR_RTC_EN[] = "RTC";
unsigned char STR_X25_EN[] = "X25";
unsigned char STR_PRINT_COMANDE_EN[] = "PRINT PINREQUEST";
unsigned char STR_INFOS_CODES_EN[] = "CODES INFORMATION";
unsigned char STR_ENVOI_NUM_SERIE_EN[] = "SEND SERIAL NO.";
unsigned char STR_ENVOI_RECLAMATION_EN[] = "SEND CLAIM";
unsigned char STR_FULL_AUTO_EN[] = "FULL AUTO :";
unsigned char STR_IMP_TELECOL_EN[] = "POLLING IMP:";
unsigned char STR_RECHARGEMENT_CODES2_EN[] = "Memory space insufficient";
unsigned char STR_RECHARGEMENT_CODES3_EN[] = "Old reports' deletion recommended";
unsigned char STR_IMP_NOM_APPLI_EN[] = "PRINT NAME SOFT";
unsigned char STR_IMP_REPORT_AUTO_EN[] = "AUTO PRINT REP.";
unsigned char STR_PRINT_ZERO_EN[] = "PRINT ZERO";
unsigned char STR_IMP_DETAIL_RECH_EN[] = "PRINT ADVRESTOCK";
unsigned char STR_IMP_RAPP_DAILY_EN[] = "PRINT DAILY REP";
unsigned char STR_MODE_DEMO_EN[] = "DEMO MODE";
unsigned char STR_RECLAMATION_EN[] = "CLAIM";
unsigned char STR_RECPT_MESSAGE_EN[] = "RECV MAIL";
unsigned char STR_CONFIRM_MESSAGE_EN[] = "MAIL CONFIRM.";
unsigned char STR_INIT_MANAGER_EN[] = "MANAGER SETTINGS";
unsigned char STR_ANNULER_EN[] = "CANCEL";
unsigned char STR_DERNIERE_VENTE_EN[] = "LAST SALE?";
unsigned char STR_ENVOI_ANNULATION_EN[] = "SEND CANCEL.";
unsigned char STR_PROPOSITION_EN[] = "ASKING";
unsigned char STR_ANNUL_VENTE_EN[] = "CANCEL SALE  ";
unsigned char STR_REFUS_EN[] = "REFUSAL";
unsigned char STR_Vendu_le_EN[] = "Sold :";
unsigned char STR_CONFIRMATION_EN[] = "CONFIRMATION";
unsigned char STR_DIFFERENT_EN[] = "DIFFERENT";
unsigned char STR_STOCK_EN[] = "STOCK";
unsigned char STR_STOCK_GENERAL_EN[] = "GENERAL STOCK";
unsigned char STR_STOCK_DESIZE_EN[] = "STOCK DETAILED";
unsigned char STR_ACTUALISE_STOCK_EN[] = "REFRESH STOCK";
unsigned char STR_IMP_RAPP_VENTE_EN[] = "PRINT SALE REPO.";
unsigned char STR_DIAL_GPRS_EN[] = "Dial GPRS";
unsigned char STR_CONNEXION_KO_EN[] = "CONNECTION FAIL";
unsigned char STR_INVALID_ENTRY_EN[] = "Invalid Entry!";
unsigned char STR_LIMIT_PORT_NUMBER_EN[] = "(0-65535): ";
unsigned char STR_APN_EN[] = "Acces Point Name";
unsigned char STR_IP_ADDRESS_EN[] = "IP Address :";
unsigned char STR_IP_PORT_EN[] = "IP Port :";
unsigned char STR_LOCAL_IP_PORT_EN[] = "Local IP Port:";
unsigned char STR_USERNAME_EN[] = "User name :";
unsigned char STR_PASSWORD_EN[] = "Password :";
unsigned char STR_AUTHENTI_EN[] = "Authentification";
unsigned char STR_PRINT_GPRS_CONFIG_EN[] = "Print GPRS sett.";
unsigned char STR_RESET_GPRS_CONFIG_EN[] = "Reset Settings";
unsigned char STR_PASSWORD_PIN_EN[] = "PIN Code SIM :";
unsigned char STR_PARAMETRES_GPRS_EN[] = "GPRS SETTINGS";
unsigned char STR_GPRS_EFFACES_EN[] = "Reseted";
unsigned char STR_NOT_SPECIFIED_EN[] = "not specified";
unsigned char STR_CONNECTION_EN[] = "CONNECTION";
unsigned char STR_SERIE_EN[] = "Serial Link ...";
unsigned char STR_STANDARD_EN[] = "STANDARD";
unsigned char STR_ITEM_CODE_EN[] = "SALE";
unsigned char STR_ITEM_MENU_EN[] = "MENU";
unsigned char STR_ENREGISTRER_EN[] = "";
unsigned char STR_VOTRE_TPE_EN[] = "";
unsigned char STR_VERIFICATION_EN[] = "CHECKING";
unsigned char STR_NOUVEAU_SMS_EN[] = "NEW SMS...";
unsigned char STR_INITIALISATION_EN[] = "INIT.";
unsigned char STR_LOGICIEL_EN[] = "SOFTWARE";
unsigned char STR_A_ECHOUER_EN[] = "FAILED";
unsigned char STR_VEUILLEZ_REDEMMARER_EN[] = "PLS RESTART";
unsigned char STR_SERVEUR_CENTRE_EN[] = "SERVER";
unsigned char STR_CONFIG_AUTO_EN[] = "AUTO CONFIG";
unsigned char STR_MENU_PLANNING_EN[] = "PLANNING MENU";
unsigned char STR_MENU_PRINT_EN[] = "PRINTING MENU";
unsigned char STR_MENU_CONNECTION_EN[] = "CONNECTION MENU";
unsigned char STR_PLUS_DE_PAPIER_EN[] = "NO PAPER";
unsigned char STR_PAPIER_REMPLACE_EN[] = "PAPER OK";
unsigned char STR_FIN_PRINT_EN[] = "END PRINITNG";
unsigned char STR_TICKET_EN[] = "TICKET";
unsigned char STR_DHCP_EN[] = "DHCP";
unsigned char STR_IP_POS_EN[] = "IP TERMINAL";
unsigned char STR_MASQUE_SS_RESEAU_EN[] = "NETWORK MASK";
unsigned char STR_PASSERELLE_EN[] = "GATEWAY";
unsigned char STR_DNS_1_EN[] = "DNS 1";
unsigned char STR_DNS_2_EN[] = "DNS 2";
unsigned char STR_ETHERNET_SETTINGS_EN[] = "ETHERNET PARAM";
unsigned char STR_MENU_ETHERNET_EN[] = "MENU ETHERNET";
unsigned char STR_ETHERNET_EN[] = "ETHERNET";
unsigned char STR_VEUILLEZ_EN[] = "PLEASE";
unsigned char STR_PATIENTER_EN[] = "WAIT...";
unsigned char STR_MULTISALE_EN[] = "MULTISALE";
unsigned char STR_ARRETER_VENTE_EN[] = "STOP SALE ?";
unsigned char STR_REPRENDRE_VENTE_EN[] = "CONTINU SALE ?";
unsigned char STR_DOUBLEPAPER_EN[] = "DOUBLE PAPER";
unsigned char STR_REPORT_DISPO_EN[] = "AVAILABLE REPORT:";
unsigned char STR_REPORT_BY_SALER_EN[] = "BY CASHIER";
unsigned char STR_REPORT_BY_NETWORK_EN[] = "BY NETWORK";
unsigned char STR_GLOBAL_CAISSIER_REPORT_EN[] = "CASHIER REPORT";
unsigned char STR_REPORT_NETWORK_EN[] = "NETWORK REPORT";
unsigned char STR_TEMPORAIRE_EN[] = "TEMPORARY";
unsigned char STR_REPORT_VENTES_EN[] = "SALES REPORT";
unsigned char STR_CHOIX_RACCOURCI_EN[] = "SHORTCUT";
unsigned char STR_PRINT_RACCOURCI_EN[] = "PRINT LIST";
unsigned char STR_TITRE_LISTE_RACCOURCI_EN[] = "------";
unsigned char STR_USE_MODE_DEGRADE_EN[] = "SECOND MODE ?";
unsigned char STR_GESTION_EQUIPE_EN[] = "SHIFT MANAGEMENT";
unsigned char STR_EQUIPE_EN_COURS_EN[] = "SHIFT ON GOING..";
unsigned char STR_DEMARRER_SERVICE_EQUIPE_EN[] = "START SHIFT";
unsigned char STR_ARRETER_SERVICE_EQUIPE_EN[] = "STOP SHIFT";
unsigned char STR_PLEASE_PRINT_EN[] = "PLEASE PRINT";
#ifndef DUBAI
unsigned char STR_SHIFT_REPORT_EN[] = "SHIFT REPORT";
unsigned char STR_MENU_REPORT_SHIFT_EN[] = "SHIFT REPORT";
unsigned char STR_MENU_REPORT__CURRENT_SHIFT_EN[] = "CURRENT SHIFT";
#else
unsigned char STR_SHIFT_REPORT_EN[] = "DAY END REPORT";
unsigned char STR_MENU_REPORT_SHIFT_EN[] = "DAY END REPORT";
unsigned char STR_MENU_REPORT__CURRENT_SHIFT_EN[] = "CURRENT SHIFT";
#endif
unsigned char STR_SHIFT_CASHIER_REPORT_EN[] = "SHIFT CASH. REP.";
unsigned char STR_EQUIPE_EN[] = "SHIFT";
unsigned char STR_DU_EN[] = "FROM";
unsigned char STR_AU_EN[] = "TO";
unsigned char STR_INACTIF_EN[] = "INACTIVE";
unsigned char STR_NO_CURRENT_SHIFT_EN[] = "NO CURRENT SHIFT";
unsigned char STR_NAME_EN[] = "Name :";
unsigned char STR_SOLDE_EN[] = "Balance:";
unsigned char STR_SITUATION_CLIENT_EN[] = "MERCHANT SOLDE";
unsigned char STR_RESTOCK_CAPACITY_EN[] = "PINS RESTOCK CAP.:";
unsigned char STR_CREDIT_CLIENT_EN[] = "Merchant Credit";
unsigned char STR_CREDIT_AUTORISE_EN[] = "Credit allowed:";
unsigned char STR_QUANTITE_OK_EN[] = "QUANTITIES OK ?";
unsigned char STR_QUANTITE_EN[] = "QUANTITIES";
unsigned char STR_INVOICED_AMOUNT_EN[] = "INVOICED AMOUNT:";
unsigned char STR_MERCHANT_ID_EN[] = "MERCHANT ID :";
unsigned char STR_SALESMAN_ID_EN[] = "SALESMAN ID :";
unsigned char STR_CHECK_ORDER_EN[] = "CHECK ORDER";
unsigned char STR_CHECKING_ORDER_EN[] = "CHECKING ORDER..";
unsigned char STR_VALIDATE_ORDER_EN[] = "VALIDATE ORDER ?";
unsigned char STR_INCOMPLETE_ORDER_EN[] = "INCOMPLETE ORDER";
unsigned char STR_PB_ORDER_EMPTY_EN[] = "ORDER EMPTY !";
unsigned char STR_PB_ORDER_AMOUNT_EN[] = "AMOUNT !";
unsigned char STR_PB_ORDER_MERCHANT_ID_EN[] = "MANAGER ID !";
unsigned char STR_PB_ORDER_TERMINAL_ID_EN[] = "TERMINAL ID !";
unsigned char STR_PB_ORDER_SALESMAN_ID_EN[] = "SALESMAN ID !";
unsigned char STR_PB_ORDER_PASSWORD_EN[] = "PASSWORD !";
unsigned char STR_EXIT_ORDER_EN[] = "EXIT ORDER ?";
unsigned char STR_SEND_ORDER_EN[] = "SEND ORDER ...";
unsigned char STR_ORDER_VALIDATED_EN[] = "ORDER VALIDATED";
unsigned char STR_ORDER_REFUSED_EN[] = "ORDER REFUSED !";
unsigned char STR_ORDER_FAILED_EN[] = "ORDER  FAILED !";
unsigned char STR_PENDING_ORDER_EN[] = "PENDING ORDER";
unsigned char STR_NO_ORDER_EN[] = "NO ORDER";
unsigned char STR_ORDER_NUMBER_EN[] = "ORDER NUMBER";
unsigned char STR_ORDER_EN[] = "ORDER";
unsigned char STR_TICKET_MERCHANT_ID_EN[] = "Merchant Id:";
unsigned char STR_TICKET_SALESMAN_ID_EN[] = "Salesman Id:";
unsigned char STR_TICKET_TERMINAL_ID_EN[] = "Terminal Id:";
unsigned char STR_SALESMAN_COPY_EN[] = "SALESMAN COPY";
unsigned char STR_MERCHANT_COPY_EN[] = "MERCHANT COPY";
unsigned char STR_SUMMARY_EN[] = "SUMMARY";
unsigned char STR_PINS_QUANTITY_EN[] = "Pins Quantity: ";
unsigned char STR_FACE_VALUE_EN[] = "Face Value: ";
unsigned char STR_PAID_EN[] = "Paid: ";
unsigned char STR_MERCHANT_SIGNATURE_EN[] = "Merchant Signature:";
unsigned char STR_SIGNATURE_EN[] = "Signature:";
unsigned char STR_BAD_SALESMAN_EN[] = "BAD SALESMAN";
unsigned char STR_AUTHENTIFICATION_MAJ_EN[] = "AUTHENTICATION";
unsigned char STR_PRODUCT_UNAVAILABLE_EN[] = "PRODUCT UNAVAILABLE";
unsigned char STR_FOR_THIS_MERCHANT_EN[] = "FOR THIS MERCHANT";
unsigned char STR_SERVER_STOCK_EMPTY_EN[] = "SERV.STOCK EMPTY";
unsigned char STR_INSUFFICIENT_CREDIT_EN[] = "INSUFFIC. CREDIT";
unsigned char STR_BAD_MERCHANT_ID_EN[] = "BAD MERCHANT ID";
unsigned char STR_OR_TERMINAL_ID_EN[] = "OR TERMINAL ID";
unsigned char STR_ORDER_MODE_EN[] = "ECC ORDER MODE";
unsigned char STR_STOCK2_EN[] = "STOCK";
unsigned char STR_PERC_DISCOUNT_EN[] = "%%%% DISCOUNT";
unsigned char STR_SCAN_BARCODE_EN[] = "SCAN BARCODE ...";
unsigned char STR_TRY_AGAIN_EN[] = "TRY AGAIN ?";
unsigned char STR_PLEASE_INPUT_EN[] = "PLEASE INPUT";
unsigned char STR_VALID_POURC_EN[] = "A VALID %%%%";
unsigned char STR_MERCHANT_SERIAL_EN[] = "MERCHANT SERIAL:";
unsigned char STR_SERIAL_NUMBER_EN[] = "SERIAL NUMBER";
unsigned char STR_ORDER_PREVIEW_EN[] = "ORDER PREVIEW";
unsigned char STR_OPERATION_REFUSED_EN[] = "OPERATION REFUSED";
unsigned char STR_OPERATION_FAILED_EN[] = "OPERATION FAILED";
unsigned char STR_NO_EN[] = "NO";
unsigned char STR_DTU_EN[] = "DIRECT TOP UP";
unsigned char STR_TELEPHONE_EN[] = "Phone number :";
unsigned char STR_CONFIRMER_TRANSACTION_EN[] = "CONTINUE TRANS.";
unsigned char STR_IMP_CONFIRM_DTU_EN[] = "DTU:PRINT CONF.";
unsigned char STR_PASSWORD_PARTIE_1_EN[] = "CODE 1";
unsigned char STR_PASSWORD_PARTIE_2_EN[] = "CODE 2";
unsigned char STR_RESET_CODE_EN[] = "RESET CODE";
unsigned char STR_CHANGE_DISCOUNT_EN[] = "CHANGE DISCOUNT";
unsigned char STR_SALESMAN_NAME_EN[] = "Salesman name:";
unsigned char STR_MERCHANT_NAME_EN[] = "Merchant name:";
unsigned char STR_SOFT_DOWNLOAD_EN[] = "DOWNLOAD SOFT.";
unsigned char STR_REASON_EN[] = "REASON:";
unsigned char STR_NOT_ALLOWED_FOR_EN[] = "NOT ALLOWED FOR";
unsigned char STR_THIS_MERCHANT_EN[] = "THIS MERCHANT";
unsigned char STR_GET_SALESMAN_EN[] = "GET SALESMAN";
unsigned char STR_INFORMATIONS_EN[] = "INFORMATIONS";
unsigned char STR_REEL_V32BIS_EN[] = "V32 BIS(14400)";
unsigned char STR_PLEASE_CHECK_EN[] = "PLEASE CHECK";
unsigned char STR_PENDING_ORDERS_EN[] = "PENDING ORDERS";
unsigned char STR_PARAM_DOWNLOAD_EN[] = "Parameter";
unsigned char STR_SALESMAN_CREDIT_EN[] = "Salesman Credit:";
unsigned char STR_PHYSICAL_CARDS_STOCK_EN[] = "Physical Cards Stock:";
unsigned char STR_CASH_ORDER_EN[] = "CASH ORDER";
unsigned char STR_CONSIGN_ORDER_EN[] = "CONSIGN ORDER";
unsigned char STR_RETURN_ORDER_EN[] = "RETURN ORDER";
unsigned char STR_ACTIVATION_NUMBER_EN[] = "Activation number:";
unsigned char STR_EXPIRY_DATE_EN[] = "Expiry date:";
unsigned char STR_SN_EN[] = "SN:";
unsigned char STR_CURRENT_DEPOSIT_EN[] = "Current Deposit";
unsigned char STR_SR_EN[] = "SR";
unsigned char STR_CUSTOMER_COPY_EN[] = "(Customer Copy)";
unsigned char STR_MERCHANT_COPY2_EN[] = "(Merchant Copy)";
unsigned char STR_POWERED_BY_EN[] = "Powered by";
unsigned char STR_TRACE_NO_EN[] = "Trace No:";
unsigned char STR_RESPONSE_CODE_EN[] = "Response Code:";
unsigned char STR_ERROR_MSG_EN[] = "Message:";	// Modified by Kim_LinHB 2013-12-17 v4.78 removed "Error "
unsigned char STR_PINS_RESTOCKED_EN[] = "Pins Restocked:";
// Added by Kim_LinHB 2014/11/4
unsigned char STR_CASHIER_LOGIN_EN[] = "Cashier Login";
unsigned char STR_TRANS_MODE_EN[] = "Transaction Mode";
unsigned char STR_TRANS_OFFLINE_EN[] = "OFFLINE";
unsigned char STR_TRANS_ONLINE_EN[] = "ONLINE";
unsigned char STR_SENDING_EN[] = "SENDING";
unsigned char STR_RECEIVING_EN[] = "RECEIVING";
// Add End
//Added by Allen 2016/03/16
unsigned char STR_VOUCHER_NUMBER_EN[] = "Voucher number:";
unsigned char STR_RECHARGE_NNUMBER_EN[] = "Recharge Number:";
//Add End

unsigned char *gl_pStr_EN[] = 
{
	STR_DEFAUT_NUMERO_PAD_PRINC_EN,
	STR_DEFAUT_NUMERO_PAD_SEC_EN,
	STR_DEFAUT_ADRESSE_X25_EN,
	STR_AUTHENTIFICATION_EN,
	STR_EUR_EN,
	STR_BLANC_EN,
	STR_TAB_EN,
	STR_AUTHENTI_PAP_EN,
	STR_AUTHENTI_SHAP_EN,
	STR_VIDE_EN,
	STR_ETOILES_EN,
	STR_GPRS_EN,
	STR_PPP_EN,
	STR_ETOILES2_EN,
	STR_TIRETS_EN,
	STR_CHOIX_OPERATEUR_EN,
	STR_PASSWORD_DISPLAY_EN,
	STR_ERROR_EN,
	STR_COUPER_LE_TICKET_EN,
	STR_PRESS_ENTER_EN,
	STR_VAL_CANCEL_EN,
	STR_VAL_CANCEL_COR_EN,
	STR_IDENT_MANAGER_EN,
	STR_PASSWORD_SECRET_EN,
	STR_PASSWORDS_CASHIERS_EN,
	STR_PASSWORD_CASHIER_EN,
	STR_TIME_SOFTWAREDOWNLOAD_EN,
	STR_TIME_SALESPOLLING_EN,
	STR_TIME_SETTINGSDOWNLOAD_EN,
	STR_PRINT_PARAM_EN,
	STR_NUMERO_PAD_EN,
	STR_NUMERO_PAD_SECOURS_EN,
	STR_MENU_PPP_EN,
	STR_NUM_TLCHGT_EN,
	STR_ID_TERMINAL_EN,
	STR_TYPE_IMPRIMANTE_EN,
	STR_REINIT_APPLI_EN,
	STR_INFOS_TRACE_EN,
	STR_NUMEROTATION_EN,
	STR_FIN_CONNEXION_EN,
	STR_PRINT_EN,
	STR_ON_GOING_EN,
	STR_TICKET_CLIENT_EN,
	STR_TICKET_MANAGER_EN,
	STR_DUPLICATA2_EN,
	STR_NON_DISPONIBLE_EN,
	STR_PAS_D_OPERATION_EN,
	STR_DONE_EN,
	STR_DEJA_PRESENT_EN,
	STR_REPORT_COMMER_EN,
	STR_REPORT_CASHIER_EN,
	STR_REPORT_DAILY_EN,
	STR_EFFACEMENT_DES_EN,
	STR_RAPP_VAL_ANN_EN,
	STR_PASSWORD_MANAGER_EN,
	STR_ENTRER_CODE_EN,
	STR_REPORTS_EN,
	STR_APPLICATION_EN,
	STR_INITIALISEE_EN,
	STR_PARAMETRES_APPLI_EN,
	STR_INCOMPLETS_EN,
	STR_TICKET_ABANDON_EN,
	STR_ATTENTE_REPONSE_EN,
	STR_SERVEUR_EN,
	STR_MEMOIRE_PLEINE_EN,
	STR_ACTIVER_TELECH_EN,
	STR_ANNUL_TELECH_EN,
	STR_TELECHARGEMENT_EN,
	STR_ACTIVE_EN,
	STR_DESACTIVE_EN,
	STR_MODIFICATION_EN,
	STR_ENTRER_LE_CODE_EN,
	STR_CONNEXION_OK_EN,
	STR_NUMEROTATION_OK_EN,
	STR_CONNEXION_EN,
	STR_SERVEUR_KO_EN,
	STR_NUMERO_OCCUPE_EN,
	STR_NUMERO_INTERDIT_EN,
	STR_PAS_DE_PORTEUSE_EN,
	STR_LINE_ABSENTE_EN,
	STR_ABANDON_EN,
	STR_PROBLEME_MODEM_EN,
	STR_PRODUCT_EN,
	STR_GESTION_RECH_EN,
	STR_INGEVOUCHER_EN,
	STR_RECHARGEMENT_EN,
	STR_LANCER_RECHARGE_EN,
	STR_PASSWORDS_EN,
	STR_TELEPARAMETRAGE_EN,
	STR_TELEPARAMETRAGE_PRINT_EN,
	STR_A_FAIRE_EN,
	STR_DEJA_EFECTUE_EN,
	STR_TABLE_OPERATEURS_EN,
	STR_TABLE_PRODUCTS_EN,
	STR_TABLE_TICKET_EN,
	STR_TABLE_MAINTENANCE_EN,
	STR_TABLE_TERMINAL_EN,
	STR_TABLE_HORODATAGE_EN,
	STR_ECHEC_EN,
	STR_SUCCES_EN,
	STR_IDENTIFICATION_EN,
	STR_VENTE_EN,
	STR_SALESPOLLING_EN,
	STR_INFO_TELECOL_EN,
	STR_DEMANDE_VERSION_EN,
	STR_REEL_EN,
	STR_REEL_V22_EN,
	STR_SIMUL_EN,
	STR_PINS_EXPIRED_EN,
	STR_PINS_EXPIRED2_EN,
	STR_PINS_USED_EN,
	STR_PINS_USED2_EN,
	STR_ANOMALIE_VENTE_EN,
	STR_ANOMALIE_VENTE2_EN,
	STR_INTERDIT_EN,
	STR_COMMANDE_EN,
	STR_PARAM_ENREGISTRE_EN,
	STR_VAL_POUR_ENTRER_EN,
	STR_NOM_CATEGORY_EN,
	STR_NOM_PRODUCT_EN,
	STR_ID_TERMINAL_Min_EN,
	STR_ID_COMM_EN,
	STR_NUM_TRANS_EN,
	STR_VALEUR_EN,
	STR_No_SERIE_EN,
	STR_FIN_VALIDITE_EN,
	STR_PASSWORD_ERREUR_EN,
	STR_Op_Min_EN,
	STR_RECAPITULATIF_EN,
	STR_NB_CODES_CHARGES_EN,
	STR_NB_CODES_A_CHARGER_EN,
	STR_Amount_Tot_EN,
	STR_TOTAL_EN,
	STR_CASHIER_Min_EN,
	STR_Nb_Codes_Telecol_EN,
	STR_Envoi_EN,
	STR_SALESPOLLING2_EN,
	STR_NB_CODES_EN,
	STR_TYPE_IMPRIMANTE_Min_EN,
	STR_Serv_MDP_EN,
	STR_HOUR_EN,
	STR_ETAT_DU_STOCK_EN,
	STR_DISP_EN,
	STR_VEND_EN,
	STR_IDENT_EN,
	STR_Version_Ticket_EN,
	STR_Version_Category_EN,
	STR_Version_Product_EN,
	STR_Version_Maintenance_EN,
	STR_Version_Terminal_EN,
	STR_Version_Horodatage_EN,
	STR_RECHARGEMENT_CODES_EN,
	STR_REPORT_EN,
	STR_MANAGER_EN,
	STR_CASHIER_EN,
	STR_CASHIER_NB_AMOUNT_EN,
	STR_PRODUCT_NB_AMOUNT_EN,
	STR_PXUNITAIRE_EN,
	STR_NB_EN,
	STR_AMOUNT_EN,
	STR_DUPLICATA_EN,
	STR_TELECHARGEMENT_APPLI_EN,
	STR_RECHARGEMENT_CODES_2_EN,
	STR_SALESPOLLING_2_EN,
	STR_PAS_DE_TELECH_EN,
	STR_PAS_DE_RECHARGE_EN,
	STR_PAS_DE_TELECOL_EN,
	STR_PAS_DE_TELEPARA_EN,
	STR_PLUS_DE_CODE_EN,
	STR_DISPONIBLE_EN,
	STR_ON_LINE_EN,
	STR_TITRE_TICKET_PARAMETRE_EN,
	STR_SOUS_TITRE_MANAGER_EN,
	STR_SOUS_TITRE_PRODUCT_EN,
	STR_SOUS_TITRE_TERMINAL_EN,
	STR_SOUS_TITRE_CONNEXION_EN,
	STR_SOUS_TITRE_TELECHARGEMENT_EN,
	STR_SOUS_TITRE_CASHIERS_EN,
	STR_SERVICE_EN,
	STR_DEMARRE_EN,
	STR_ARRETE_EN,
	STR_DEMARRER_SERVICE_EN,
	STR_ARRETER_SERVICE_EN,
	STR_VISUALISE_STOCK_EN,
	STR_PRINT_STOCK_EN,
	STR_CHARGER_CLE_EN,
	STR_CHARGEMENT_CLE_EN,
	STR_CREDIT_EPUISE_EN,
	STR_PASSWORD_UPPER_EN,
	STR_REPORT_DAILY_PRINT_EN,
	STR_STOCK_SERVEUR_EN,
	STR_EPUISE_EN,
	STR_NOUVEAU_CODE_EN,
	STR_CONFIRMER_CODE_EN,
	STR_AUTRE_VENTE_EN,
	STR_PRINT_CODE_BARRE_EN,
	STR_PRINT_LOGO_EN,
	STR_OUI_EN,
	STR_NON_EN,
	STR_VALIDE_COMMANDE_EN,
	STR_CHARGEMENT_LOGO_EN,
	STR_MASTER_APPLI_EN,
	STR_TYPE_CNX_TELECH_EN,
	STR_RTC_EN,
	STR_X25_EN,
	STR_PRINT_COMANDE_EN,
	STR_INFOS_CODES_EN,
	STR_ENVOI_NUM_SERIE_EN,
	STR_ENVOI_RECLAMATION_EN,
	STR_FULL_AUTO_EN,
	STR_IMP_TELECOL_EN,
	STR_RECHARGEMENT_CODES2_EN,
	STR_RECHARGEMENT_CODES3_EN,
	STR_IMP_NOM_APPLI_EN,
	STR_IMP_REPORT_AUTO_EN,
	STR_PRINT_ZERO_EN,
	STR_IMP_DETAIL_RECH_EN,
	STR_IMP_RAPP_DAILY_EN,
	STR_MODE_DEMO_EN,
	STR_RECLAMATION_EN,
	STR_RECPT_MESSAGE_EN,
	STR_CONFIRM_MESSAGE_EN,
	STR_INIT_MANAGER_EN,
	STR_ANNULER_EN,
	STR_DERNIERE_VENTE_EN,
	STR_ENVOI_ANNULATION_EN,
	STR_PROPOSITION_EN,
	STR_ANNUL_VENTE_EN,
	STR_REFUS_EN,
	STR_Vendu_le_EN,
	STR_CONFIRMATION_EN,
	STR_DIFFERENT_EN,
	STR_STOCK_EN,
	STR_STOCK_GENERAL_EN,
	STR_STOCK_DESIZE_EN,
	STR_ACTUALISE_STOCK_EN,
	STR_IMP_RAPP_VENTE_EN,
	STR_DIAL_GPRS_EN,
	STR_CONNEXION_KO_EN,
	STR_INVALID_ENTRY_EN,
	STR_LIMIT_PORT_NUMBER_EN,
	STR_APN_EN,
	STR_IP_ADDRESS_EN,
	STR_IP_PORT_EN,
	STR_LOCAL_IP_PORT_EN,
	STR_USERNAME_EN,
	STR_PASSWORD_EN,
	STR_AUTHENTI_EN,
	STR_PRINT_GPRS_CONFIG_EN,
	STR_RESET_GPRS_CONFIG_EN,
	STR_PASSWORD_PIN_EN,
	STR_PARAMETRES_GPRS_EN,
	STR_GPRS_EFFACES_EN,
	STR_NOT_SPECIFIED_EN,
	STR_CONNECTION_EN,
	STR_SERIE_EN,
	STR_STANDARD_EN,
	STR_ITEM_CODE_EN,
	STR_ITEM_MENU_EN,
	STR_ENREGISTRER_EN,
	STR_VOTRE_TPE_EN,
	STR_VERIFICATION_EN,
	STR_NOUVEAU_SMS_EN,
	STR_INITIALISATION_EN,
	STR_LOGICIEL_EN,
	STR_A_ECHOUER_EN,
	STR_VEUILLEZ_REDEMMARER_EN,
	STR_SERVEUR_CENTRE_EN,
	STR_CONFIG_AUTO_EN,
	STR_MENU_PLANNING_EN,
	STR_MENU_PRINT_EN,
	STR_MENU_CONNECTION_EN,
	STR_PLUS_DE_PAPIER_EN,
	STR_PAPIER_REMPLACE_EN,
	STR_FIN_PRINT_EN,
	STR_TICKET_EN,
	STR_DHCP_EN,
	STR_IP_POS_EN,
	STR_MASQUE_SS_RESEAU_EN,
	STR_PASSERELLE_EN,
	STR_DNS_1_EN,
	STR_DNS_2_EN,
	STR_ETHERNET_SETTINGS_EN,
	STR_MENU_ETHERNET_EN,
	STR_ETHERNET_EN,
	STR_VEUILLEZ_EN,
	STR_PATIENTER_EN,
	STR_MULTISALE_EN,
	STR_ARRETER_VENTE_EN,
	STR_REPRENDRE_VENTE_EN,
	STR_DOUBLEPAPER_EN,
	STR_REPORT_DISPO_EN,
	STR_REPORT_BY_SALER_EN,
	STR_REPORT_BY_NETWORK_EN,
	STR_GLOBAL_CAISSIER_REPORT_EN,
	STR_REPORT_NETWORK_EN,
	STR_TEMPORAIRE_EN,
	STR_REPORT_VENTES_EN,
	STR_CHOIX_RACCOURCI_EN,
	STR_PRINT_RACCOURCI_EN,
	STR_TITRE_LISTE_RACCOURCI_EN,
	STR_USE_MODE_DEGRADE_EN,
	STR_GESTION_EQUIPE_EN,
	STR_EQUIPE_EN_COURS_EN,
	STR_DEMARRER_SERVICE_EQUIPE_EN,
	STR_ARRETER_SERVICE_EQUIPE_EN,
	STR_PLEASE_PRINT_EN,
#ifndef DUBAI
	STR_SHIFT_REPORT_EN,
	STR_MENU_REPORT_SHIFT_EN,
	STR_MENU_REPORT__CURRENT_SHIFT_EN,
#else
	STR_SHIFT_REPORT_EN,
	STR_MENU_REPORT_SHIFT_EN,
	STR_MENU_REPORT__CURRENT_SHIFT_EN,
#endif
	STR_SHIFT_CASHIER_REPORT_EN,
	STR_EQUIPE_EN,
	STR_DU_EN,
	STR_AU_EN,
	STR_INACTIF_EN,
	STR_NO_CURRENT_SHIFT_EN,
	STR_NAME_EN,
	STR_SOLDE_EN,
	STR_SITUATION_CLIENT_EN,
	STR_RESTOCK_CAPACITY_EN,
	STR_CREDIT_CLIENT_EN,
	STR_CREDIT_AUTORISE_EN,
	STR_QUANTITE_OK_EN,
	STR_QUANTITE_EN,
	STR_INVOICED_AMOUNT_EN,
	STR_MERCHANT_ID_EN,
	STR_SALESMAN_ID_EN,
	STR_CHECK_ORDER_EN,
	STR_CHECKING_ORDER_EN,
	STR_VALIDATE_ORDER_EN,
	STR_INCOMPLETE_ORDER_EN,
	STR_PB_ORDER_EMPTY_EN,
	STR_PB_ORDER_AMOUNT_EN,
	STR_PB_ORDER_MERCHANT_ID_EN,
	STR_PB_ORDER_TERMINAL_ID_EN,
	STR_PB_ORDER_SALESMAN_ID_EN,
	STR_PB_ORDER_PASSWORD_EN,
	STR_EXIT_ORDER_EN,
	STR_SEND_ORDER_EN,
	STR_ORDER_VALIDATED_EN,
	STR_ORDER_REFUSED_EN,
	STR_ORDER_FAILED_EN,
	STR_PENDING_ORDER_EN,
	STR_NO_ORDER_EN,
	STR_ORDER_NUMBER_EN,
	STR_ORDER_EN,
	STR_TICKET_MERCHANT_ID_EN,
	STR_TICKET_SALESMAN_ID_EN,
	STR_TICKET_TERMINAL_ID_EN,
	STR_SALESMAN_COPY_EN,
	STR_MERCHANT_COPY_EN,
	STR_SUMMARY_EN,
	STR_PINS_QUANTITY_EN,
	STR_FACE_VALUE_EN,
	STR_PAID_EN,
	STR_MERCHANT_SIGNATURE_EN,
	STR_SIGNATURE_EN,
	STR_BAD_SALESMAN_EN,
	STR_AUTHENTIFICATION_MAJ_EN,
	STR_PRODUCT_UNAVAILABLE_EN,
	STR_FOR_THIS_MERCHANT_EN,
	STR_SERVER_STOCK_EMPTY_EN,
	STR_INSUFFICIENT_CREDIT_EN,
	STR_BAD_MERCHANT_ID_EN,
	STR_OR_TERMINAL_ID_EN,
	STR_ORDER_MODE_EN,
	STR_STOCK2_EN,
	STR_PERC_DISCOUNT_EN,
	STR_SCAN_BARCODE_EN,
	STR_TRY_AGAIN_EN,
	STR_PLEASE_INPUT_EN,
	STR_VALID_POURC_EN,
	STR_MERCHANT_SERIAL_EN,
	STR_SERIAL_NUMBER_EN,
	STR_ORDER_PREVIEW_EN,
	STR_OPERATION_REFUSED_EN,
	STR_OPERATION_FAILED_EN,
	STR_NO_EN,
	STR_DTU_EN,
	STR_TELEPHONE_EN,
	STR_CONFIRMER_TRANSACTION_EN,
	STR_IMP_CONFIRM_DTU_EN,
	STR_PASSWORD_PARTIE_1_EN,
	STR_PASSWORD_PARTIE_2_EN,
	STR_RESET_CODE_EN,
	STR_CHANGE_DISCOUNT_EN,
	STR_SALESMAN_NAME_EN,
	STR_MERCHANT_NAME_EN,
	STR_SOFT_DOWNLOAD_EN,
	STR_REASON_EN,
	STR_NOT_ALLOWED_FOR_EN,
	STR_THIS_MERCHANT_EN,
	STR_GET_SALESMAN_EN,
	STR_INFORMATIONS_EN,
	STR_REEL_V32BIS_EN,
	STR_PLEASE_CHECK_EN,
	STR_PENDING_ORDERS_EN,
	STR_PARAM_DOWNLOAD_EN,
	STR_SALESMAN_CREDIT_EN,
	STR_PHYSICAL_CARDS_STOCK_EN,
	STR_CASH_ORDER_EN,
	STR_CONSIGN_ORDER_EN,
	STR_RETURN_ORDER_EN,
	STR_ACTIVATION_NUMBER_EN,
	STR_EXPIRY_DATE_EN,
	STR_SN_EN,
	STR_CURRENT_DEPOSIT_EN,
	STR_SR_EN,
	STR_CUSTOMER_COPY_EN,
	STR_MERCHANT_COPY2_EN,
	STR_POWERED_BY_EN,
	STR_TRACE_NO_EN,
	STR_RESPONSE_CODE_EN,
	STR_ERROR_MSG_EN,
	STR_PINS_RESTOCKED_EN,
	// Added by Kim_LinHB 2014/11/4
	STR_CASHIER_LOGIN_EN,
	STR_TRANS_MODE_EN,
	STR_TRANS_OFFLINE_EN,
	STR_TRANS_ONLINE_EN,
	STR_SENDING_EN,
	STR_RECEIVING_EN,
	// Add End
	//Added by Allen 2016/03/16
	STR_VOUCHER_NUMBER_EN,
	STR_RECHARGE_NNUMBER_EN,
	//Add End
};

//extern unsigned char *gl_pStr_EN[];

#endif
